Repository Ice-Cream-Team/VanillaBot, pull requests merged in 2020-03, with the labels that each got.

#13 Specifying the token now works through either the --token or --tokenfile switches.
  .gitignore
  README.md
  index.js
Labels: good to merge

#14 !vb Prefix, multiple command implementations
  index.js
Labels: NEEDS dev review

#17 Dev/powell/b
  index.js
Labels: HOLD

#22 Initialize Command Files for future formatting issue
  cmd_game.js
  cmd_help.js
  cmd_mal.js
  cmd_server.js
Labels: good to merge

#26 Fixed bug with catching errors while fetching game server information
  index.js
Labels: NEEDS dev review

#29 Completed the modifications to the generateHalp routine. Now it used Embed to generate its message.
  index.js
Labels: NEEDS dev review, enhancement

#30 Fix bug where bot crashes after not finding an anime on MAL
  index.js
Labels: enhancement

#33 MAL Search Emeded implementation, Node Module bug isolation
  index.js
  node_modules/myanimelists/src/services/Parser.js
Labels: NEEDS dev review, documentation, enhancement

#36 Can now access commands through separate files, added cmd_game command
  cmd_game.js
  cmd_help.js
  cmd_mal.js
  cmd_server.js
  cmds/cmd_cmds.js
  cmds/cmd_game.js
  cmds/cmd_help.js
  cmds/cmd_mal.js
  cmds/cmd_server.js
  index.js
Labels: NEEDS dev review, enhancement

#41 If else - > switch case, kys - > kill, added server list command
  README.md
  cmds/cmd_cmds.js
  cmds/cmd_game.js
  cmds/cmd_server.js
  index.js
Labels: documentation, enhancement

#44 Changed from switch case and trimmed down index.js,
  cmds/cmd_game.js
  cmds/cmd_help.js
  cmds/cmd_mal.js
  cmds/cmd_server.js
  index.js
Labels: enhancement

#47 Added owner command object and command permission checking.
  cmds/cmd_cmds.js
  cmds/cmd_owner.js
  index.js
Labels: NEEDS dev review, enhancement

#48 Regression Testing feature, staging/testing environment config
  README.md
  index.js
Labels: NEEDS dev review, documentation, enhancement
